sudo: false
language: python

python:
  # - 2.7
  # - 3.4
  # - 3.5
  - 3.6

env:
  global:
    - NUMPY_VERSION=1.12
    - GALA_VERSION='dev' # only works with dev version on master!

matrix:
  include:

    # - python: 3.5
    #   env: NUMPY_VERSION=1.10

    - python: 3.6
      env: NUMPY_VERSION=1.11

install:
  - source setup-travis.sh

script:
  - cd tests
  - py.test -v
