sudo: false
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:

    env: NUMPY_VERSION=1.10
    env: NUMPY_VERSION=1.11
    env: NUMPY_VERSION=1.12

    env: GALA_VERSION='dev'
    env: GALA_VERSION=0.1.3

install:
  - source setup-travis.sh

script:
  - py.test -v
