name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  build:
    name: "py${{ matrix.python-version }} on ${{ matrix.os }}, Gala ${{ matrix.gala-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        gala-version: ["dev", "stable"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get install libgsl-dev

      - name: Install Gala dev version
        if: matrix.gala-version == 'dev'
        run: |
          python -m pip install git+https://github.com/adrn/gala.git

      - name: Install Gala latest stable version
        if: matrix.gala-version == 'stable'
        run: |
          python -m pip install gala

      - name: Build and install this package
        run: |
          python -m pip install pytest
          python -m pip install -e .

      - name: Run tests
        run: |
          cd tests
          pytest test_simple.py
