name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "py${{ matrix.python-version }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        gala-dev: [false, true]
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install libgsl-dev

      - name: Install Gala dev version
        if: matrix.gala-dev
        run: |
          pip install git+https://github.com/adrn/gala.git

      - name: Install Gala latest stable version
        if: matrix.gala-dev != true
        run: |
          pip install astro-gala

      - name: Build and install this package
        run: |
          python -m pip install pytest
          python -m pip install -e .

      - name: Run tests
        run: |
          cd tests
          pytest test_simple.py
